package Issue1;

import java.io.IOException;

public class Issue1 {

	public static void main(String[] args) throws IOException{
		System.out.println("プログラムが起動しました");
		throw new IOException();
		// TODO 自動生成されたメソッド・スタブ
		/*
		String s =null;
		try {
			System.out.println(s.length());
		} catch (NullPointerException e) {
			System.out.println("NullPointerExceptionをcatchしました。");
			System.out.println("--スタックトレースは(ここから)--");
			// TODO 自動生成された catch ブロック
			e.printStackTrace();
			System.out.println("--スタックトレースは(ここまで)--");
		}

		try {
			int num = Integer.parseInt("三");
		} catch (NumberFormatException e) {
			// TODO 自動生成された catch ブロック
			System.out.println("変換不能な引数です");
			e.printStackTrace();
		}
		*/
	}


}
